### ISSUE TITLE
Can I using some deleted source? (I'm sorry to ask.)

### ISSUE THREAD

**Issue by HumanKR** [bbpanzu/bb-fnf-mods#13]
Ok, ok. before I start, I'm sorry to bring up a bad story before we start.
I was making mods when you upload sky mod source-code.
And I was downloaded sources for translation and learn programming more.
also I thought it would be pretty cool to have an ending in my mod, so I added your EndingState code and continued working.
Then... As you know, mod and codes have been deleted due to... yea..
I was forgot ask about it. also I afraid it.
I'm confused if I can continue to use it because I'm not good at haxeflixel.

So the point is, please allow to use the EndingState source...
I really want to use this QAQ

Have a nice day.

**Comment by fnffanspritemaker** [comment]
search up or prees "/"
and search sky

**Comment by HumanKR** [comment]
> search up or prees "/"
> and search sky
There is no need to deal with this issue any more.
Because bbpanzu used endingstate.hx source code in other mods now.
And I think it would be a little rude to pick up past deleted codes and take them.
