### ISSUE TITLE
Missing Wav Files

### ISSUE THREAD

**Issue by GoofyGuyWhoCantAnimate** [bbpanzu/bb-fnf-mods#26]
Obviously the main reason is that there's nothing to extract/no folders for it but for carol roll, over half of the sounds are missing (Uso~!(No Kidding~!), Mattaku Mou (Oh... Come on!), Nyan(meow), Hoi, Nandeyanen (What the heck in Kansai intonation), Hai!, nh?, and Party!!) Maybe **stems** could fix the problem?

**Comment by GoofyGuyWhoCantAnimate** [comment]
Or if you still have the **files**, adding them to a folder as said at the start.

**Comment by noonononnonnoo** [comment]
It would really help if he did add all his commonly used audios like the Uso! and Hai! sound.

**Comment by GoofyGuyWhoCantAnimate** [comment]
to be honest, those and mattaku mou are the only ones i care about. i'm desperate at this point

**Comment by noonononnonnoo** [comment]
Yes, there's so many assets that BB needs to release. Like maybe his old Boyfriend soundfont? And these anime-like wavs.

**Comment by GoofyGuyWhoCantAnimate** [comment]
Apparently someone got in contact with him to get one of the carol voice files which I wish i was able to do but it doesn't seem like there's anywhere to do that, although I doubt he'd notice.

**Comment by GoofyGuyWhoCantAnimate** [comment]
dk why i bothered :/

**Comment by GoofyGuyWhoCantAnimate** [comment]
how do u close issues

**Comment by GoofyGuyWhoCantAnimate** [comment]
finally! i found them! they were in a vol 1 kawaii voice sample video

**Comment by noonononnonnoo** [comment]
Video link?

**Comment by GoofyGuyWhoCantAnimate** [comment]
https://www.youtube.com/watch?v=cbn8ktwYFWw

**Comment by GoofyGuyWhoCantAnimate** [comment]
theres a few with forbidden symbols in the name so just copy and paste this into them ?

**Comment by noonononnonnoo** [comment]
Give me the link, GoofyGuyWhoCantAnimate

**Comment by GoofyGuyWhoCantAnimate** [comment]
sorry, thought you used it already, here https://www.youtube.com/watch?v=cbn8ktwYFWw

**Comment by GoofyGuyWhoCantAnimate** [comment]
did you use it? because i needa delete that reply

**Comment by GoofyGuyWhoCantAnimate** [comment]
oh, also here's the carol voices if you dont have them already https://github.com/bbpanzu/bb-fnf-mods/blob/29aa07eb8a448cf50bcdc8f445d82db46c3c85b3/FL%20Studio%20thingies/carol%20voice%20noted.mp3

**Comment by noonononnonnoo** [comment]
Oh that's pretty interesting, I thought she used a voice actor.

**Comment by GoofyGuyWhoCantAnimate** [comment]
no thats for the song

**Comment by noonononnonnoo** [comment]
I know.

**Comment by GoofyGuyWhoCantAnimate** [comment]
oh

**Comment by noonononnonnoo** [comment]
I thought a voice actor was used for the song.

**Comment by GoofyGuyWhoCantAnimate** [comment]
i mean it might be, it doesnt sound like him

**Comment by noonononnonnoo** [comment]
No, listening to the raw audio it's either UTAU or some other vocaloid/AI Voice. It's definitely not a real person.

**Comment by GoofyGuyWhoCantAnimate** [comment]
Oh, okay.

**Comment by noonononnonnoo** [comment]
It's also just interesting to listen to the unedited source audio and seeing how it was all out of beat and how BB chopped it up perfectly.

**Comment by GoofyGuyWhoCantAnimate** [comment]
true

**Comment by GoofyGuyWhoCantAnimate** [comment]
started off with complaining about missing sounds to whatever this is

**Comment by GoofyGuyWhoCantAnimate** [comment]
k now that i think of it, that does not sound real at all

**Comment by GoofyGuyWhoCantAnimate** [comment]
even if they're 0cc files, its still annoying

**Comment by noonononnonnoo** [comment]
0cc files are for famitrack I'm pretty sure, and the og versions of those songs are in their respective folders.
