### ISSUE TITLE
where is the carol roll flp

### ISSUE THREAD

**Issue by SoftWasTaken** [bbpanzu/bb-fnf-mods#40]

**Comment by leafy11FL** [comment]
are you blind

**Comment by leafy11FL** [comment]
ok i guess you wont find the carol roll flp then

**Comment by leafy11FL** [comment]
so basically its somewhere in this repository

**Comment by leafy11FL** [comment]
here https://github.com/bbpanzu/bb-fnf-mods/blob/main/FL%20Studio%20thingies/Carol%20Roll.flp

**Comment by leafy11FL** [comment]
like close the issue
