### ISSUE TITLE
Many FLA files are corrupted

### ISSUE THREAD

**Issue by SleepySeer** [bbpanzu/bb-fnf-mods#62]
Me and a few friends are trying to do a reskin mod for the homestuck mod, but all of the fla files are corrupted. I tried repair techniques and none of those seemed to work. From what I've seen on here, it's not just that mods fla files. Many fla files are corrupt or will not open on users animate. If there could be a fix to this or another location the files are at that would be great.

**Comment by SteveGoblin1** [comment]
I'm 98% sure it's just adobe being silly, go back one version or two. this happened when I was tryna mess with the tankmen flas.

**Comment by SleepySeer** [comment]
This did in fact work and we ended up finishing everything
