### ISSUE TITLE
I can't find audio sample on FL Studio projects of Golf Minigame mod (reopen)

### ISSUE THREAD

**Issue by HumanKR** [bbpanzu/bb-fnf-mods#8]
![image](https://user-images.githubusercontent.com/45139720/117168936-943b9600-ae03-11eb-8ac7-98d92b023c38.png)
this samples is not exist on this github
except pixelText.ogg (cuz we can find in fnf gamefile)
can you add this samples?

**Comment by bbpanzu** [comment]
whoops here https://www.youtube.com/watch?v=9LXa_4Dn-n8

**Comment by IYO1585** [comment]
Alright! now it seems working fine!
Thanks a lot!

**Comment by HumanKR** [comment]
![image](https://user-images.githubusercontent.com/45139720/119285764-c19a9780-bc7d-11eb-8bf0-802606f916d4.png)
ok there is also that golf2 things doesn't exist too
and... actually now we can't download Kontakt 5. can only download kontakt 6.
maybe we can find that vst search on google but... you know
just keep in mind yep. the most important thing is another two missing files

**Comment by HumanKR** [comment]
1. that insert actually not useful or... he forgot it
2. we have to pay if want to use kontakt. is not free plugins.
